# Take temperature in Celsius and convert to Fahrenheit...............................

print("Take a temperature in Celsius and Convert to Fahrenheit :")
# taking user input...........................
c = float(input("Enter the temperature in celsius : "))
# Printing the value assigned to variales ................
print("Celsius =",c)
# Applying Square and Cude Operation.................
F = (c * 9/5) + 32
#Printing the final output..........
print(f"The Conversion of Celsius {c} in Fahrenheit is:",F) # used F-String in this...............