# Checking that a person is eligible to vote...............................

print("Checking that a person is eligible to vote")
# taking user input...........................
name = input("Enter your name : ")
age = int(input("Enter your age : "))
# Printing the value assigned to variales ................
print("Hello =",name)
print(f"You are {age} years old") # used F-String in this...............
# Applying Square and Cude Operation.................
if age >= 18:
    print("You are eligible to vote")
else:
    print("You are Not eligible to vote")    
