# Take a number from user and:
# Print its square
# Print its cube

print("Take a numbers from user and print their :\nIt's Square\nIt's Cube")
# taking user input...........................
a = int(input("Enter the number : "))
# Printing the value assigned to variales ................
print("a =",a)
# Applying Square and Cude Operation.................
Square = a ** 2
Cube = a ** 3
#Printing the final output..........
print(f"The Square of {a} is:",Square) # used F-String in this...............
print(f"The Cube of {a} is:",Cube)