# Create a list.....
marks = [89, 96, 89, 55, 63, 75]

# 1st slicing type.......
print(marks[1:4])

# 2nd slicing type.......
print(marks[ : 5])

# 3rd slicing type.......
print(marks[0 : ])

# 4th slicing type.......
print(marks[2 : len(marks)])

# 5th slicing type.......
print(marks[-4 : -1])